language: go
env:
  -  GO111MODULE=on
sudo: required
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.19.x"
  - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - make check